config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: 'public/homes#top'
  scope module: :public do
    # ゲスト用
    devise_scope :user do
      post "users/guest_sign_in", to: "users#guest_sign_in"
    end

    get 'about' => 'homes#about'
    get 'users/mypage' => 'users#mypage'
    resources :users, only:  [:show]
    get 'users/introduction/edit' => 'users#edit'
    patch 'users/introduction' => 'users#update'
    patch 'users/withdraw' => 'users#withdraw'
    resources :bookmarks, only:  [:index]
    resources :posts, only:  [:new, :index, :create, :show, :edit, :update, :destroy] do
      resource :bookmarks, only:  [:create, :destroy]
      get 'puzzle' => 'posts#puzzle'
      resources :post_comments, only:  [:create, :destroy]
    end
    resources :searches, only:  [:index]
    resources :tags, only:  [:index]
    resources :opinion_boxes, only:  [:new, :create]
  end

  namespace :admin do
    devise_scope :admin do
    get "/" => 'sessions#new'
    end
    resources :users, only:  [:index, :edit, :update, :destroy]
    resources :posts, only:  [:index, :show, :edit, :update, :destroy]
    resources :post_comments, only:  [:index, :show, :edit, :update, :destroy]
    resources :tags, only:  [:index, :edit, :update, :destroy]
    resources :searches, only: [:index]
    resources :opinion_boxes, only: [:index, :show, :update, :destroy] do
      patch 'read' => 'opinion_boxes#read'
      patch 'unread' => 'opinion_boxes#unread'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :post_tags

  validates :name, presence: true, uniqueness: true
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @tags = Tag.all.page(params[:page]).per(10)
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if@tag.update(tag_params)
      redirect_to admin_tags_path
    else
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.delete
    redirect_to admin_tags_path
  end

  private
  def tag_params
    params.require(:tag).permit(:name, :is_active)
  end
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/views/admin/tags/_admin_tag_form.html.erb
<table class="table table-hover margin-y">
  <thead>
    <tr>
      <th>#</th>
      <th>タグ名</th>
      <th class="text-center">ステータス</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% tags.each do |tag| %>
    <tr>
      <td class="align-middle"><%= tag.id %></td>
      <td class="align-middle"><%= tag.name %></td>
      <td class="align-middle text-center">
        <% if tag.is_active %>
          <span class="text-success"><strong>正常<strong></span>
        <% else %>
          <span class="text-danger">問題あり</span>
        <% end %>
      </td>
      <td class="text-center"><%= link_to "編集", edit_admin_tag_path(tag.id), class: "btn btn-success" %></td>
      <td class="text-center"><%= link_to "削除", admin_tag_path(tag.id), method: :delete, class: "btn btn-danger", "data-confirm" => "本当に削除しますか？" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/tags/edit.html.erb
<div class="container fit-content">
  <h4 class="margin-y">管理者側：投稿編集</h4>
  <%= form_with model: @tag, url: admin_tag_path do |f| %>
  <%= render "layouts/form_errors", model: @tag %>
  <div class="margin-y mx-auto">
    <div class="field">
      <div class="d-sm-flex padding-sm-y">
        <span class="label-width mb-2 mb-sm-0">投稿ID</span>
        <span class="mx-5 mx-sm-0"><%= @tag.id %></span>
      </div>
      <div class="d-sm-flex padding-sm-y">
        <%= f.label :name, "タグ名", class: "label-width mb-2 mb-sm-0"  %>
        <%= f.text_field :name, placeholder: "#{@tag.name}", class: "field-width form-control border-secondary rounded-1"  %>
      </div>
      <div class="d-sm-flex padding-sm-y">
        <p class="label-width mb-2 mb-sm-0">ステータス</p>
        <div>
          <span>
            <%= f.radio_button :is_active, true, class: "form-check-input" %>
            <%= f.label :is_active_true, "正常" %>
          </span>
          <span class="margin-x">
            <%= f.radio_button :is_active, false, class: "form-check-input" %>
            <%= f.label :is_active_false, "問題あり" %>
          </span>
        </div>
      </div>
    </div>
  </div>
  <div class="text-center">
    <%= f.submit '変更を保存する', class: "btn btn-success" %>
  </div>
  <% end %>
</div>

app/views/admin/tags/index.html.erb
<div class="container margin-y w-75">
  <%= render 'admin/searches/admin_search_form' %>
</div>

<div class="container">
  <h2>管理者側：タグ一覧</h2>
  <div class="mx-auto margin-y">
    <%= render 'admin/tags/admin_tag_form', tags: @tags %>
  </div>
  <div class="margin-y">
    <%= paginate @tags, window: 1, left: 1, right: 1 %>
  </div>
</div>