config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: 'public/homes#top'
  scope module: :public do
    # ゲスト用
    devise_scope :user do
      post "users/guest_sign_in", to: "users#guest_sign_in"
    end

    get 'about' => 'homes#about'
    get 'users/mypage' => 'users#mypage'
    resources :users, only:  [:show]
    get 'users/introduction/edit' => 'users#edit'
    patch 'users/introduction' => 'users#update'
    patch 'users/withdraw' => 'users#withdraw'
    resources :bookmarks, only:  [:index]
    resources :posts, only:  [:new, :index, :create, :show, :edit, :update, :destroy] do
      resource :bookmarks, only:  [:create, :destroy]
      get 'puzzle' => 'posts#puzzle'
      resources :post_comments, only:  [:create, :destroy]
    end
    resources :searches, only:  [:index]
    resources :tags, only:  [:index]
    resources :opinion_boxes, only:  [:new, :create]
  end

  namespace :admin do
    devise_scope :admin do
    get "/" => 'sessions#new'
    end
    resources :users, only:  [:index, :edit, :update, :destroy]
    resources :posts, only:  [:index, :show, :edit, :update, :destroy]
    resources :post_comments, only:  [:index, :show, :edit, :update, :destroy]
    resources :tags, only:  [:index, :edit, :update, :destroy]
    resources :searches, only: [:index]
    resources :opinion_boxes, only: [:index, :show, :update, :destroy] do
      patch 'read' => 'opinion_boxes#read'
      patch 'unread' => 'opinion_boxes#unread'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/opinion_box.rb
class OpinionBox < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
end

app/controllers/admin/opinion_boxes_controller.rb
class Admin::OpinionBoxesController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    range = params[:range]
    case range
    when 'unread'
      @opinion_boxes = OpinionBox.where(is_read: false).page(params[:page])
    when 'read'
      @opinion_boxes = OpinionBox.where(is_read: true).page(params[:page])
    when "all"
      @opinion_boxes = OpinionBox.all.page(params[:page])
    else
      @opinion_boxes = OpinionBox.all.page(params[:page])
    end
  end

  def show
    @opinion_box = OpinionBox.find(params[:id])
  end

  def update
    opinion = OpinionBox.find(params[:id])
    if opinion.is_read == true
      opinion.update(is_read: false)
    else
      opinion.update(is_read: true)
    end
    redirect_back(fallback_location: root_path)
  end

  def read
    @opinion_boxes = OpinionBox.where(is_read: false).page(params[:page])
    opinion = OpinionBox.find(params[:opinion_box_id])
    opinion.update(is_read: true)
    render :read
  end

  def unread
    @opinion_boxes = OpinionBox.where(is_read: true).page(params[:page])
    opinion = OpinionBox.find(params[:opinion_box_id])
    opinion.update(is_read: false)
    render :unread
  end

  def destroy
    opinion_box = OpinionBox.find(params[:id])
    opinion_box.delete
    redirect_to admin_opinion_boxes_path(range: "all")
  end

  private
  def opinion_params
  	params.require(:opinion_box).permit(:title, :content)
  end
end

app/helpers/admin/opinion_boxes_helper.rb
module Admin::OpinionBoxesHelper
end

app/views/admin/opinion_boxes/_admin_opinion_box.html.erb
<% opinion_boxes.each do |opinion| %>
<div class="card my-3 col">
  <div class="m-3">
    <h4><%= opinion.title %></h4>
    <p class="card-text"><%= opinion.content %></p>
    <div class="mt-1 d-flex justify-content-between align-items-center">
      <div>
      <span class="me-3">ユーザー名：<strong><%= opinion.user.name.truncate(30) %></strong></span>
      <span class="text-muted"><%= opinion.created_at.strftime('%Y年%m月%d日') %></span>
      </div>
      <div>
        <%= link_to "詳細", admin_opinion_box_path(opinion.id), class: "btn btn-primary btn-sm px-3 me-3"%>
        <% if opinion.is_read == true %>
          <%= link_to "未読に戻す", admin_opinion_box_unread_path(opinion.id), class: "btn btn-success btn-sm padding-x", method: :patch, remote: true %>
        <% else %>
          <%= link_to "既読", admin_opinion_box_read_path(opinion.id), class: "btn btn-success btn-sm padding-x", method: :patch, remote: true %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/admin/opinion_boxes/index.html.erb
<div class="container">
  <h2 class="margin-y">管理者側：ご意見箱</h2>
  <div class="mx-auto mx-2">
    <%= link_to "未読", admin_opinion_boxes_path(range: "unread"), id: "unread", class: "order btn btn-light rounded-pill px-3 me-2 order_button_active"%>
    <%= link_to "既読済", admin_opinion_boxes_path(range: "read"), id: "read", class: "order btn btn-light rounded-pill px-3 me-2"%>
    <%= link_to "全て", admin_opinion_boxes_path(range: "all"), id: "all", class: "order btn btn-light rounded-pill px-3 me-2"%>
  </div>

  <div>
    <% if @opinion_boxes.exists? %>
      <% if params[:range] == "all" %>
        <table class='table table-hover margin-y'>
          <thead>
            <tr>
              <th>#</th>
              <th>投稿者</th>
              <th>タイトル</th>
              <th class="text-center">ステータス</th>
            </tr>
          </thead>
          <tbody>
            <% @opinion_boxes.each do |opinion| %>
              <tr data-href="opinion_boxes/<%= opinion.id %>" class="mouse-link">
                <td><%= opinion.id %></td>
                <td><%= opinion.user.name.truncate(30) %></td>
                <td><%= opinion.title.truncate(30) %></td>
                <td class="text-center">
                  <% if opinion.is_read %>
                    <span>既読済</span>
                  <% else %>
                    <span>未読</span>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <div id="opinion_status_button">
          <%= render 'admin/opinion_boxes/admin_opinion_box', opinion_boxes: @opinion_boxes %>
        </div>
      <% end %>
    <% end %>
  </div>

  <% if @opinion_boxes %>
  <div class="margin-y">
    <%= paginate @opinion_boxes, window: 1, left: 1, right: 1 %>
  </div>
  <% end %>
</div>

<script>
  $(function(){
    $('tr[data-href]').on('click', function(){
      location.href = $(this).data('href');
    });
    if (window.location.href.indexOf("range=all") > -1) {
      $('.order_button_active').removeClass('order_button_active');
      $('#all').addClass('order_button_active');
    } else if (window.location.href.indexOf("range=unread") > -1) {
      $('.order_button_active').removeClass('order_button_active');
      $('#unread').addClass('order_button_active');
    } else if (window.location.href.indexOf("range=read") > -1) {
      $('.order_button_active').removeClass('order_button_active');
      $('#read').addClass('order_button_active');
    }
  });
</script>

app/views/admin/opinion_boxes/read.js.erb
$('#opinion_status_button').html("<%= j(render 'admin/opinion_boxes/admin_opinion_box', opinion_boxes: @opinion_boxes) %>");

app/views/admin/opinion_boxes/show.html.erb
<div class="container">
  <div>
    <h2 class="margin-y">管理者側：意見詳細</h2>
    <table class="table table-bordered mb-0">
      <tbody>
        <tr>
          <th class="w-25">意見ID</th>
          <td><%= @opinion_box.id %></td>
        </tr>
        <tr>
          <th>投稿者</th>
          <td data-href="../users/<%= @opinion_box.user.id %>/edit" class="mouse-link" style="color: #0693e3"><%= @opinion_box.user.name %></td>
        </tr>
        <tr>
          <th>タイトル</th>
          <td><%= @opinion_box.title %></td>
        </tr>
        <tr>
          <th>内容</th>
          <td><%= @opinion_box.content %></td>
        </tr>
        <tr>
          <th>投稿日</th>
          <td><%= @opinion_box.created_at.strftime("%Y年%m月%d日 %H:%M:%S") %></td>
        </tr>
        <tr>
          <th>ステータス</th>
          <td>
            <% if @opinion_box.is_read %>
              <span>既読済</span>
            <% else %>
              <span>未読</span>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>

    <div class="my-3 text-end">
      <% if @opinion_box.is_read %>
        <%= link_to "未読に戻す", admin_opinion_box_path(@opinion_box.id), class: "btn btn-success padding-x me-3", method: :patch %>
      <% else %>
        <%= link_to "既読済", admin_opinion_box_path(@opinion_box.id), class: "btn btn-success padding-x me-3", method: :patch %>
      <% end %>
      <%= link_to "削除", admin_opinion_box_path(@opinion_box.id), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-danger padding-x" %>
    </div>
  </div>
</div>

<script>
  $(function(){
    $('td[data-href]').on('click', function(){
      location.href = $(this).data('href');
    });
  });
</script>

app/views/admin/opinion_boxes/unread.js.erb
$('#opinion_status_button').html("<%= j(render 'admin/opinion_boxes/admin_opinion_box', opinion_boxes: @opinion_boxes) %>");