config/routes.rb
Rails.application.routes.draw do
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  root to: 'public/homes#top'
  scope module: :public do
    # ゲスト用
    devise_scope :user do
      post "users/guest_sign_in", to: "users#guest_sign_in"
    end

    get 'about' => 'homes#about'
    get 'users/mypage' => 'users#mypage'
    resources :users, only:  [:show]
    get 'users/introduction/edit' => 'users#edit'
    patch 'users/introduction' => 'users#update'
    patch 'users/withdraw' => 'users#withdraw'
    resources :bookmarks, only:  [:index]
    resources :posts, only:  [:new, :index, :create, :show, :edit, :update, :destroy] do
      resource :bookmarks, only:  [:create, :destroy]
      get 'puzzle' => 'posts#puzzle'
      resources :post_comments, only:  [:create, :destroy]
    end
    resources :searches, only:  [:index]
    resources :tags, only:  [:index]
    resources :opinion_boxes, only:  [:new, :create]
  end

  namespace :admin do
    devise_scope :admin do
    get "/" => 'sessions#new'
    end
    resources :users, only:  [:index, :edit, :update, :destroy]
    resources :posts, only:  [:index, :show, :edit, :update, :destroy]
    resources :post_comments, only:  [:index, :show, :edit, :update, :destroy]
    resources :tags, only:  [:index, :edit, :update, :destroy]
    resources :searches, only: [:index]
    resources :opinion_boxes, only: [:index, :show, :update, :destroy] do
      patch 'read' => 'opinion_boxes#read'
      patch 'unread' => 'opinion_boxes#unread'
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :post_id, presence: true
  validates :user_id, presence: true

end

app/models/opinion_box.rb
class OpinionBox < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :post_image
  belongs_to :user
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :bookmarks, dependent: :destroy
  has_many :bookmarked_users, through: :bookmarks, source: :user
  has_many :post_comments, dependent: :destroy
  has_many :post_accesses, dependent: :destroy

  validates :title, presence: true #, length: {maximum: 30}
  validates :post_image, presence: true

  # 投稿にあるタグを更新＋新規タグを保存
  def get_tag(sent_tags)
    current_tags = tags.pluck(:name)
    old_tags = current_tags - sent_tags
    new_tags = sent_tags - current_tags
    # 古いタグを消す
    old_tags.each do |old|
      tags.delete Tag.find_by(name: old)
    end
    # 新しいタグを保存
    new_tags.each do |new|
      new_post_tag = Tag.find_or_create_by(name: new)
      tags << new_post_tag
    end
  end

  # post_image画像サイズ変更用
  def get_image(width, height)
    unless post_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      post_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    post_image.variant(resize_to_limit: [width, height]).processed
  end

  # 特定のpostのbookmarkをしているかどうか
  def bookmarked_by?(user)
    bookmarks.exists?(user_id: user.id)
  end
end

app/models/post_access.rb
class PostAccess < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :post_id, presence: true
  validates :user_id, presence: true
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true, length: {maximum: 150}
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag

  validates :post_id, presence: true
  validates :tag_id, presence: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :post_tags, dependent: :destroy, foreign_key: 'tag_id'
  has_many :posts, through: :post_tags

  validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { maximum: 30 }

  has_many :posts, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :bookmark_posts, -> { order(created_at: :desc) }, through: :bookmarks, source: :post
  has_many :post_comments, dependent: :destroy
  has_many :post_accesses, dependent: :destroy
  has_many :opinion_boxes, dependent: :destroy

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @posts = Post.all.page(params[:page]).per(10)
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
    @tag_list = @post.tags.pluck(:name).join(' ')
  end

  def update
    @post = Post.find(params[:id])
    tag_list = params[:post][:tag_name].gsub("　", " ").split(nil)
    if @post.update(post_params)
      @post.get_tag(tag_list)
      redirect_to admin_post_path(@post.id)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.delete
    redirect_to admin_posts_path
  end

  private
  def post_params
    params.require(:post).permit(:post_image, :title, :content, :is_public, :is_active)
  end
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @tags = Tag.all.page(params[:page]).per(10)
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def update
    @tag = Tag.find(params[:id])
    if@tag.update(tag_params)
      redirect_to admin_tags_path
    else
      render :edit
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.delete
    redirect_to admin_tags_path
  end

  private
  def tag_params
    params.require(:tag).permit(:name, :is_active)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @users = User.all.page(params[:page]).per(10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/opinion_boxes_helper.rb
module Admin::OpinionBoxesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/searches_helper.rb
module Admin::SearchesHelper
end

app/helpers/admin/tags_helper.rb
module Admin::TagsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <p class="m-0 align-items-center py-2">
    <i class="fa-regular fa-copyright"></i> CopyRight ImagelaPuzzle.inc
  </p>
</footer>

app/views/layouts/_form_errors.html.erb
<% if model.errors.any? %>
<div class="my-4">

<h4 class="text-danger"><%= model.errors.count %>件のエラーが発生しました。</h4>
<ul>
  <% model.errors.full_messages.each do |message| %>
  <li><%= message %></li>
  <% end %>
</ul>

</div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="p-0 navbar navbar-expand-lg navbar-dark" style="background: #213555">
    <div class="nav-layout container-fluid px-3">
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag 'logo_long_white.png', style: "width: 230px"%>
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
      data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup"
      aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse justify-content-end" id="navbarNavAltMarkup" >
        <div class="navbar-nav">
          <% if request.fullpath.include? "/admin" %>
          <!--管理者側ログイン後ナビバー-->
            <% if admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "会員一覧", admin_users_path, class: 'nav-link px-3'  %>
            </li>
            <li class="nav-item">
              <%= link_to "投稿一覧", admin_posts_path, class: 'nav-link px-3'  %>
            </li>
            <li class="nav-item">
              <%= link_to "タグ一覧", admin_tags_path, class: 'nav-link px-3'  %>
            </li>
            <li class="nav-item">
              <%= link_to "コメント一覧", admin_post_comments_path, class: 'nav-link px-3'  %>
            </li>
            <li class="nav-item">
              <%= link_to "ご意見箱", admin_opinion_boxes_path(range: "unread"), class: 'nav-link px-3' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link px-3'  %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to "Home", root_path, class: 'nav-link px-3'  %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_admin_session_path, class: 'nav-link px-3' %>
            </li>
            <% end %>
          <% elsif user_signed_in? %>
          <!--ゲストログイン後ナビバー-->
            <% if current_user.email == 'guest@example.com' %>
            <li class="nav-item">
              <%= link_to "Home", root_path, class: 'nav-link px-3' %>
            </li>
            <li class="nav-item">
              <%= link_to "画像一覧", posts_path, class: 'nav-link px-3' %>
            </li>
            <li class="nav-item">
              <%= link_to "タグ検索", tags_path, class: 'nav-link px-3' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link px-3'  %>
            </li>
            <% else %>
            <!--ユーザー側ログイン後ナビバー-->
            <li class="nav-item">
              <%= link_to "マイページ", users_mypage_path, class: 'nav-link px-3' %>
            </li>
            <li class="nav-item">
              <%= link_to "画像一覧", posts_path, class: 'nav-link px-3' %>
            </li>
            <li class="nav-item">
              <%= link_to "新規投稿", new_post_path, class: 'nav-link px-3' %>
            </li>
            <li class="nav-item">
              <%= link_to "ブックマーク", bookmarks_path, class: 'nav-link px-3' %>
            </li>
            <li class="nav-item">
              <%= link_to "タグ検索", tags_path, class: 'nav-link px-3' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link px-3'  %>
            </li>
            <% end %>
          <% else %>
          <!--ログイン前ナビバー-->
            <li class="nav-item">
              <%= link_to "Home", root_path, class: 'nav-link px-3'  %>
            </li>
            <li class="nav-item">
              <%= link_to "新規登録", new_user_registration_path, class: 'nav-link px-3' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_user_session_path, class: 'nav-link px-3' %>
            </li>
          <% end %>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_post_form.html.erb
  <div class="d-sm-flex padding-sm-y align-items-center">
      <%= f.label :title, "タイトル", class: "label-width mb-2 mb-sm-0"  %>
      <%= f.text_field :title, placeholder: "", class: " form-control border-secondary rounded-1", style: "width: 320px" %>
  </div>

  <div class="d-sm-flex padding-sm-y justify-content-between align-items-baseline">
      <%= f.label :content, "キャプション", class: "label-width mb-2 mb-sm-0"  %>
      <%= f.text_area :content, placeholder: "", rows: "5", class: "form-control border-secondary rounded-1", style: "width: 320px" %>
  </div>

  <div class="d-sm-flex padding-sm-y align-items-center">
      <%= f.label :tag_name, "タグ", class: "label-width mb-2 mb-sm-0"  %>
      <% if current_page?(new_post_path) %>
      <%= f.text_field :tag_name, placeholder: "例：写真　花", class: "form-control border-secondary rounded-1", style: "width: 320px" %>
      <% else %>
      <%= f.text_field :tag_name, placeholder: "#{@tag_list}", value: @tag_list, class: " form-control border-secondary rounded-1", style: "width: 320px" %>
      <% end %>
  </div>

  <div class="d-sm-flex padding-sm-y align-items-center">
    <p class="label-width mb-2 mb-sm-0">公開範囲</p>
    <div>
      <span>
        <%= f.radio_button :is_public, true, class: "form-check-input" %>
        <%= f.label :is_public_true, "公開"%>
      </span>
      <span class="margin-x">
        <%= f.radio_button :is_public, false, class: "form-check-input" %>
        <%= f.label :is_public_false, "非公開" %>
      </span>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all'%>

    <%= javascript_pack_tag 'application'%>
    <!--FontAwesome-->
    <script src="https://kit.fontawesome.com/<%= ENV['FONTAWESOME_ID'] %>.js" crossorigin="anonymous"></script>
    <!--Isotope-->
    <script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <% if flash[:notice].present? %>
    <div class="text-center margin-y">
      <%= flash[:notice]%>
    </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>